import { PadItem } from '../types';

export const DEFAULT_PADS: PadItem[] = [
  // 12 Harmonic Ambient Worship Pads (All 12 keys)
  {
    id: 'pad-1',
    name: 'Pad C (Dó Maior - Atmosfera)',
    category: 'worship',
    musicalKey: 'C',
    url: '/uploads/audio/pad_c.wav',
    originalFileName: 'pad_c.wav',
    fileSize: 529244,
    duration: 6,
    color: '#3b82f6',
    isLoop: true,
    volume: 0.8,
    pan: 0,
    filterCutoff: 20000,
    fadeInTime: 1.5,
    fadeOutTime: 2.5,
    isCustomUpload: false,
    cloudStored: true,
    createdAt: '2026-09-09T16:12:34.155Z',
    hotkey: '1'
  },
  {
    id: 'pad-2',
    name: 'Pad C# (Dó# Maior - Deep)',
    category: 'worship',
    musicalKey: 'C#',
    url: '/uploads/audio/pad_csharp.wav',
    originalFileName: 'pad_csharp.wav',
    fileSize: 529244,
    duration: 6,
    color: '#6366f1',
    isLoop: true,
    volume: 0.8,
    pan: 0,
    filterCutoff: 20000,
    fadeInTime: 1.5,
    fadeOutTime: 2.5,
    isCustomUpload: false,
    cloudStored: true,
    createdAt: '2026-09-09T16:12:34.155Z',
    hotkey: '2'
  },
  {
    id: 'pad-3',
    name: 'Pad D (Ré Maior - Brilho)',
    category: 'worship',
    musicalKey: 'D',
    url: '/uploads/audio/pad_d.wav',
    originalFileName: 'pad_d.wav',
    fileSize: 529244,
    duration: 6,
    color: '#8b5cf6',
    isLoop: true,
    volume: 0.8,
    pan: 0,
    filterCutoff: 20000,
    fadeInTime: 1.5,
    fadeOutTime: 2.5,
    isCustomUpload: false,
    cloudStored: true,
    createdAt: '2026-09-09T16:12:34.155Z',
    hotkey: '3'
  },
  {
    id: 'pad-4',
    name: 'Pad Eb (Mib Maior - Suave)',
    category: 'worship',
    musicalKey: 'Eb',
    url: '/uploads/audio/pad_dsharp.wav',
    originalFileName: 'pad_dsharp.wav',
    fileSize: 529244,
    duration: 6,
    color: '#a855f7',
    isLoop: true,
    volume: 0.8,
    pan: 0,
    filterCutoff: 20000,
    fadeInTime: 1.5,
    fadeOutTime: 2.5,
    isCustomUpload: false,
    cloudStored: true,
    createdAt: '2026-09-09T16:12:34.155Z',
    hotkey: '4'
  },
  {
    id: 'pad-5',
    name: 'Pad E (Mi Maior - Profundo)',
    category: 'worship',
    musicalKey: 'E',
    url: '/uploads/audio/pad_e.wav',
    originalFileName: 'pad_e.wav',
    fileSize: 529244,
    duration: 6,
    color: '#ec4899',
    isLoop: true,
    volume: 0.8,
    pan: 0,
    filterCutoff: 20000,
    fadeInTime: 1.5,
    fadeOutTime: 2.5,
    isCustomUpload: false,
    cloudStored: true,
    createdAt: '2026-09-09T16:12:34.155Z',
    hotkey: '5'
  },
  {
    id: 'pad-6',
    name: 'Pad F (Fá Maior - Caloroso)',
    category: 'worship',
    musicalKey: 'F',
    url: '/uploads/audio/pad_f.wav',
    originalFileName: 'pad_f.wav',
    fileSize: 529244,
    duration: 6,
    color: '#f43f5e',
    isLoop: true,
    volume: 0.8,
    pan: 0,
    filterCutoff: 20000,
    fadeInTime: 1.5,
    fadeOutTime: 2.5,
    isCustomUpload: false,
    cloudStored: true,
    createdAt: '2026-09-09T16:12:34.155Z',
    hotkey: '6'
  },
  {
    id: 'pad-7',
    name: 'Pad F# (Fá# Maior - Shimmer)',
    category: 'worship',
    musicalKey: 'F#',
    url: '/uploads/audio/pad_fsharp.wav',
    originalFileName: 'pad_fsharp.wav',
    fileSize: 529244,
    duration: 6,
    color: '#ef4444',
    isLoop: true,
    volume: 0.8,
    pan: 0,
    filterCutoff: 20000,
    fadeInTime: 1.5,
    fadeOutTime: 2.5,
    isCustomUpload: false,
    cloudStored: true,
    createdAt: '2026-09-09T16:12:34.155Z',
    hotkey: '7'
  },
  {
    id: 'pad-8',
    name: 'Pad G (Sol Maior - Celestial)',
    category: 'worship',
    musicalKey: 'G',
    url: '/uploads/audio/pad_g.wav',
    originalFileName: 'pad_g.wav',
    fileSize: 529244,
    duration: 6,
    color: '#0284c7',
    isLoop: true,
    volume: 0.8,
    pan: 0,
    filterCutoff: 20000,
    fadeInTime: 1.5,
    fadeOutTime: 2.5,
    isCustomUpload: false,
    cloudStored: true,
    createdAt: '2026-09-09T16:12:34.155Z',
    hotkey: '8'
  },
  {
    id: 'pad-9',
    name: 'Pad Ab (Láb Maior - Sereno)',
    category: 'worship',
    musicalKey: 'Ab',
    url: '/uploads/audio/pad_gsharp.wav',
    originalFileName: 'pad_gsharp.wav',
    fileSize: 529244,
    duration: 6,
    color: '#eab308',
    isLoop: true,
    volume: 0.8,
    pan: 0,
    filterCutoff: 20000,
    fadeInTime: 1.5,
    fadeOutTime: 2.5,
    isCustomUpload: false,
    cloudStored: true,
    createdAt: '2026-09-09T16:12:34.155Z',
    hotkey: '9'
  },
  {
    id: 'pad-10',
    name: 'Pad A (Lá Maior - Aveludado)',
    category: 'worship',
    musicalKey: 'A',
    url: '/uploads/audio/pad_a.wav',
    originalFileName: 'pad_a.wav',
    fileSize: 529244,
    duration: 6,
    color: '#84cc16',
    isLoop: true,
    volume: 0.8,
    pan: 0,
    filterCutoff: 20000,
    fadeInTime: 1.5,
    fadeOutTime: 2.5,
    isCustomUpload: false,
    cloudStored: true,
    createdAt: '2026-09-09T16:12:34.155Z',
    hotkey: '0'
  },
  {
    id: 'pad-11',
    name: 'Pad Bb (Sib Maior - Épico)',
    category: 'worship',
    musicalKey: 'Bb',
    url: '/uploads/audio/pad_asharp.wav',
    originalFileName: 'pad_asharp.wav',
    fileSize: 529244,
    duration: 6,
    color: '#10b981',
    isLoop: true,
    volume: 0.8,
    pan: 0,
    filterCutoff: 20000,
    fadeInTime: 1.5,
    fadeOutTime: 2.5,
    isCustomUpload: false,
    cloudStored: true,
    createdAt: '2026-09-09T16:12:34.155Z',
    hotkey: 'Q'
  },
  {
    id: 'pad-12',
    name: 'Pad B (Si Maior - Espacial)',
    category: 'worship',
    musicalKey: 'B',
    url: '/uploads/audio/pad_b.wav',
    originalFileName: 'pad_b.wav',
    fileSize: 529244,
    duration: 6,
    color: '#06b6d4',
    isLoop: true,
    volume: 0.8,
    pan: 0,
    filterCutoff: 20000,
    fadeInTime: 1.5,
    fadeOutTime: 2.5,
    isCustomUpload: false,
    cloudStored: true,
    createdAt: '2026-09-09T16:12:34.155Z',
    hotkey: 'W'
  },
  // 10 Rhythms and Percussion Loops (Samba, Pagode, Batucada, Drums)
  {
    id: 'pad-13',
    name: 'Samba Batucada Completa (100 BPM)',
    category: 'ritmo',
    bpm: 100,
    url: '/uploads/audio/loop_samba_100bpm_12.wav',
    originalFileName: 'loop_samba_100bpm_12.wav',
    fileSize: 423404,
    duration: 4.8,
    color: '#14b8a6',
    isLoop: true,
    volume: 0.8,
    pan: 0,
    filterCutoff: 20000,
    fadeInTime: 0.05,
    fadeOutTime: 0.1,
    isCustomUpload: false,
    cloudStored: true,
    createdAt: '2026-09-09T16:12:34.155Z',
    hotkey: 'E'
  },
  {
    id: 'pad-14',
    name: 'Pagode Groove & Tantan (92 BPM)',
    category: 'ritmo',
    bpm: 92,
    url: '/uploads/audio/loop_pagode_92bpm_13.wav',
    originalFileName: 'loop_pagode_92bpm_13.wav',
    fileSize: 460216,
    duration: 5.22,
    color: '#0ea5e9',
    isLoop: true,
    volume: 0.8,
    pan: 0,
    filterCutoff: 20000,
    fadeInTime: 0.05,
    fadeOutTime: 0.1,
    isCustomUpload: false,
    cloudStored: true,
    createdAt: '2026-09-09T16:12:34.155Z',
    hotkey: 'R'
  },
  {
    id: 'pad-15',
    name: 'Pandeiro Brasileiro Suingado (96 BPM)',
    category: 'percussao',
    bpm: 96,
    url: '/uploads/audio/loop_pandeiro_96bpm_14.wav',
    originalFileName: 'loop_pandeiro_96bpm_14.wav',
    fileSize: 441044,
    duration: 5,
    color: '#64748b',
    isLoop: true,
    volume: 0.8,
    pan: 0,
    filterCutoff: 20000,
    fadeInTime: 0.05,
    fadeOutTime: 0.1,
    isCustomUpload: false,
    cloudStored: true,
    createdAt: '2026-09-09T16:12:34.155Z',
    hotkey: 'T'
  },
  {
    id: 'pad-16',
    name: 'Bateria Worship Dinâmica (72 BPM)',
    category: 'ritmo',
    bpm: 72,
    url: '/uploads/audio/loop_worship_beat_72bpm_15.wav',
    originalFileName: 'loop_worship_beat_72bpm_15.wav',
    fileSize: 588044,
    duration: 6.67,
    color: '#d946ef',
    isLoop: true,
    volume: 0.8,
    pan: 0,
    filterCutoff: 20000,
    fadeInTime: 0.05,
    fadeOutTime: 0.1,
    isCustomUpload: false,
    cloudStored: true,
    createdAt: '2026-09-09T16:12:34.155Z',
    hotkey: 'Y'
  },
  {
    id: 'pad-17',
    name: 'Bateria Pop / Praise (120 BPM)',
    category: 'ritmo',
    bpm: 120,
    url: '/uploads/audio/loop_worship_beat_120bpm_16.wav',
    originalFileName: 'loop_worship_beat_120bpm_16.wav',
    fileSize: 352844,
    duration: 4,
    color: '#3b82f6',
    isLoop: true,
    volume: 0.8,
    pan: 0,
    filterCutoff: 20000,
    fadeInTime: 0.05,
    fadeOutTime: 0.1,
    isCustomUpload: false,
    cloudStored: true,
    createdAt: '2026-09-09T16:12:34.155Z',
    hotkey: 'U'
  },
  {
    id: 'pad-18',
    name: 'Surdo Marcação & Repique (104 BPM)',
    category: 'percussao',
    bpm: 104,
    url: '/uploads/audio/loop_batucada_104bpm_17.wav',
    originalFileName: 'loop_batucada_104bpm_17.wav',
    fileSize: 407120,
    duration: 4.62,
    color: '#6366f1',
    isLoop: true,
    volume: 0.8,
    pan: 0,
    filterCutoff: 20000,
    fadeInTime: 0.05,
    fadeOutTime: 0.1,
    isCustomUpload: false,
    cloudStored: true,
    createdAt: '2026-09-09T16:12:34.155Z',
    hotkey: 'I'
  },
  {
    id: 'pad-19',
    name: 'Shaker & Chocalho Condução (110 BPM)',
    category: 'percussao',
    bpm: 110,
    url: '/uploads/audio/loop_percussao_110bpm_18.wav',
    originalFileName: 'loop_percussao_110bpm_18.wav',
    fileSize: 384916,
    duration: 4.36,
    color: '#8b5cf6',
    isLoop: true,
    volume: 0.8,
    pan: 0,
    filterCutoff: 20000,
    fadeInTime: 0.05,
    fadeOutTime: 0.1,
    isCustomUpload: false,
    cloudStored: true,
    createdAt: '2026-09-09T16:12:34.155Z',
    hotkey: 'O'
  },
  {
    id: 'pad-20',
    name: 'Tamborim & Agogô Virada (108 BPM)',
    category: 'percussao',
    bpm: 108,
    url: '/uploads/audio/loop_samba_108bpm_19.wav',
    originalFileName: 'loop_samba_108bpm_19.wav',
    fileSize: 392044,
    duration: 4.44,
    color: '#a855f7',
    isLoop: true,
    volume: 0.8,
    pan: 0,
    filterCutoff: 20000,
    fadeInTime: 0.05,
    fadeOutTime: 0.1,
    isCustomUpload: false,
    cloudStored: true,
    createdAt: '2026-09-09T16:12:34.155Z',
    hotkey: 'P'
  },
  {
    id: 'pad-21',
    name: 'Bossa Nova Suave (84 BPM)',
    category: 'ritmo',
    bpm: 84,
    url: '/uploads/audio/loop_acoustic_84bpm_20.wav',
    originalFileName: 'loop_acoustic_84bpm_20.wav',
    fileSize: 504044,
    duration: 5.71,
    color: '#ec4899',
    isLoop: true,
    volume: 0.8,
    pan: 0,
    filterCutoff: 20000,
    fadeInTime: 0.05,
    fadeOutTime: 0.1,
    isCustomUpload: false,
    cloudStored: true,
    createdAt: '2026-09-09T16:12:34.155Z',
    hotkey: 'A'
  },
  {
    id: 'pad-22',
    name: 'Groove Acústico Lo-Fi (88 BPM)',
    category: 'ritmo',
    bpm: 88,
    url: '/uploads/audio/loop_acoustic_88bpm_21.wav',
    originalFileName: 'loop_acoustic_88bpm_21.wav',
    fileSize: 481134,
    duration: 5.45,
    color: '#f43f5e',
    isLoop: true,
    volume: 0.8,
    pan: 0,
    filterCutoff: 20000,
    fadeInTime: 0.05,
    fadeOutTime: 0.1,
    isCustomUpload: false,
    cloudStored: true,
    createdAt: '2026-09-09T16:12:34.155Z',
    hotkey: 'S'
  }
];
